### ISSUE TITLE
Multiple test failures with numpy 1.23

### ISSUE THREAD

**Issue by sanjayankur31** [nipy/nipy#495]
Hi folks,

The Fedora numpy maintainers are working on updating numpy to 1.23, and noticed that a number of tests fail for nipy with this version.
Would it be possible to please take a look and suggest what we should do?

Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=2137291

Errors, for your convenience:

```
======================================================================
ERROR: nipy.algorithms.statistics.formula.tests.test_formula.test_factor_term
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/formula/tests/test_formula.py", line 513, in test_factor_term
    name = np.asscalar(np.array('foo', ndt))
           ^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/numpy/__init__.py", line 311, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'asscalar'

======================================================================
ERROR: nipy.algorithms.statistics.tests.test_intrinsic_volumes.test_ec
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 190, in test_ec
    _, box1 = randombox((40,) * i)
              ^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 49, in randombox
    return edges, box(shape, edges)
                  ^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 34, in box
    data[sl] = 1
    ~~~~^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: nipy.algorithms.statistics.tests.test_intrinsic_volumes.test_ec_disjoint
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 205, in test_ec_disjoint
    box1, box2, _, _ = nonintersecting_boxes((40,)*i)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 89, in nonintersecting_boxes
    edge1, box1 = randombox(shape)
                  ^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 49, in randombox
    return edges, box(shape, edges)
                  ^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 34, in box
    data[sl] = 1
    ~~~~^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: nipy.algorithms.statistics.tests.test_intrinsic_volumes.test_lips1_disjoint
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 258, in test_lips1_disjoint
    box1, box2, edge1, edge2 = nonintersecting_boxes((30,))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 89, in nonintersecting_boxes
    edge1, box1 = randombox(shape)
                  ^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 49, in randombox
    return edges, box(shape, edges)
                  ^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 34, in box
    data[sl] = 1
    ~~~~^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: nipy.algorithms.statistics.tests.test_intrinsic_volumes.test_lips2_disjoint
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 283, in test_lips2_disjoint
    box1, box2, edge1, edge2 = nonintersecting_boxes((40,40))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 89, in nonintersecting_boxes
    edge1, box1 = randombox(shape)
                  ^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 49, in randombox
    return edges, box(shape, edges)
                  ^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 34, in box
    data[sl] = 1
    ~~~~^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: nipy.algorithms.statistics.tests.test_intrinsic_volumes.test_lips3_disjoint
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 310, in test_lips3_disjoint
    box1, box2, edge1, edge2 = nonintersecting_boxes((40,)*3)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 89, in nonintersecting_boxes
    edge1, box1 = randombox(shape)
                  ^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 49, in randombox
    return edges, box(shape, edges)
                  ^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/statistics/tests/test_intrinsic_volumes.py", line 34, in box
    data[sl] = 1
    ~~~~^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: nipy.algorithms.utils.tests.test_pca_image.test_other_axes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/utils/tests/test_pca_image.py", line 298, in test_other_axes
    pos_p = img_res2pos1(p, bv_key)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/utils/tests/test_pca_image.py", line 277, in img_res2pos1
    res['basis_projections'] = Image(bps * signs[new_axes],
                                           ~~~~~^^^^^^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: nipy.algorithms.tests.test_kernel_smooth.test_anat_smooth
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/tests/test_kernel_smooth.py", line 22, in test_anat_smooth
    smoother = LinearFilter(anat.coordmap, anat.shape)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/kernel_smooth.py", line 49, in __init__
    self._setup_kernel()
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/kernel_smooth.py", line 69, in _setup_kernel
    kernel = _crop(kernel)
             ^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/kernel_smooth.py", line 261, in _crop
    return X[slices]
           ~^^^^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: nipy.algorithms.tests.test_kernel_smooth.test_funny_coordmap
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/tests/test_kernel_smooth.py", line 41, in test_funny_coordmap
    smoother = LinearFilter(func1.coordmap, func1.shape)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/kernel_smooth.py", line 49, in __init__
    self._setup_kernel()
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/kernel_smooth.py", line 69, in _setup_kernel
    kernel = _crop(kernel)
             ^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/kernel_smooth.py", line 261, in _crop
    return X[slices]
           ~^^^^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: nipy.algorithms.tests.test_kernel_smooth.test_func_smooth
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/tests/test_kernel_smooth.py", line 60, in test_func_smooth
    smoother = LinearFilter(func.coordmap, func.shape)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/kernel_smooth.py", line 49, in __init__
    self._setup_kernel()
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/kernel_smooth.py", line 69, in _setup_kernel
    kernel = _crop(kernel)
             ^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/kernel_smooth.py", line 261, in _crop
    return X[slices]
           ~^^^^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: nipy.algorithms.tests.test_kernel_smooth.test_kernel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/tests/test_kernel_smooth.py", line 92, in test_kernel
    kernel = LinearFilter(coordmap, shape,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/kernel_smooth.py", line 49, in __init__
    self._setup_kernel()
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/kernel_smooth.py", line 69, in _setup_kernel
    kernel = _crop(kernel)
             ^^^^^^^^^^^^^
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/algorithms/kernel_smooth.py", line 261, in _crop
    return X[slices]
           ~^^^^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: nipy.core.image.tests.test_image.test_iter_axis
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/core/image/tests/test_image.py", line 293, in test_iter_axis
    assert_array_equal(s, data[slicer])
                          ~~~~^^^^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: nipy.core.utils.tests.test_generators.test_multi_slice
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/core/utils/tests/test_generators.py", line 41, in test_multi_slice
    for _, d in slice_generator(DATA, axis=[0, 1]):
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/core/utils/generators.py", line 193, in slice_generator
    yield slices, data[slices]
                  ~~~~^^^^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: nipy.core.utils.tests.test_generators.test_multi_slice_write
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/core/utils/tests/test_generators.py", line 61, in test_multi_slice_write
    write_data(a, slice_generator(DATA, axis=[0, 1]))
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/core/utils/generators.py", line 141, in write_data
    for index, data in iterable:
  File "/builddir/build/BUILD/nipy-0.5.0/build/lib.linux-x86_64-cpython-311/nipy/core/utils/generators.py", line 193, in slice_generator
    yield slices, data[slices]
                  ~~~~^^^^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

----------------------------------------------------------------------
Ran 2586 tests in 121.743s

FAILED (SKIP=12, errors=14)
```

**Comment by matthew-brett** [comment]
Thanks for this, sorry for the delay.  Term was very busy.  I think the current sources will work (as of a few seconds ago).  At least they do on my machine.   Do they work for you?

**Comment by matthew-brett** [comment]
Thanks very much for testing.  Sorry - I incompetently left in a work-in-progress build refactor.   Try now?

**Comment by musicinmybrain** [comment]
Thanks! The tests do appear to pass with 35a5f52: https://src.fedoraproject.org/rpms/python-nipy/pull-request/5

Any idea when the next release might be?

**Comment by matthew-brett** [comment]
Soon - I want to do some work on the build system.

**Comment by yarikoptic** [comment]
there were some fixes recently on this.  also in debian some tireless maintainers collected some number of patches for this matter https://salsa.debian.org/med-team/nipy/-/tree/master/debian/patches but I think they no longer apply here (ie were addressed may be?)

**Comment by sanjayankur31** [comment]
Fedora has recently also included the new Cython 3 version, and it looks like that causes some issues here also. For the time being, I'm limiting the build requirements to `Cython < 3` to work around this.

https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html

**Comment by musicinmybrain** [comment]
> Fedora has recently also included the new Cython 3 version, and it looks like that causes some issues here also. For the time being, I'm limiting the build requirements to `Cython < 3` to work around this.
> 
> https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html

Now reported separately in https://github.com/nipy/nipy/issues/508.

**Comment by musicinmybrain** [comment]
With current `main` ad688348f7677ada04b3f55fdfdcfb7163ea9c14 plus a small downstream patch to allow building with numpy 1.24 in Fedora, all of the tests are now passing, except for one weird error:

```
Doctest: nipy.interfaces.matlab.mlab_tempfile ... ok
nipy.interfaces.tests.test_mlabtemp.test_mlab_tempfile(None,) ... ok
nipy.interfaces.tests.test_mlabtemp.test_mlab_tempfile('/tmp',) ... ok
nipy.interfaces.tests.test_mlabtemp.test_mlab_tempfile('/tmp/tmpex014un7',) ... 
ok
Failure: TypeError (stat: path should be string, bytes, os.PathLike or integer, 
not NoneType) ... ERROR
nipy.labs.bindings.tests.test_array.test_array_get ... ok
nipy.labs.bindings.tests.test_array.test_array_get_block ... ok
```

```
======================================================================
ERROR: Failure: TypeError (stat: path should be string, bytes, os.PathLike or integer, not NoneType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.12/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nose/importer.py", line 162, in importFromPath
    return self.importFromDir(dir_path, fqname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nose/importer.py", line 201, in importFromDir
    if (self.sameModule(old, filename)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nose/importer.py", line 241, in sameModule
    new_path = self._dirname_if_file(filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nose/importer.py", line 225, in _dirname_if_file
    if os.path.isdir(filename):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 42, in isdir
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

----------------------------------------------------------------------
Ran 2735 tests in 106.414s  

FAILED (SKIP=2, errors=1)   
```

I’m not sure what to do about that yet, but I think it’s safe to say the regressions reported here are resolved now. Thanks for all the recent effort reviewing and merging PR’s.

**Comment by matthew-brett** [comment]
I guess this is with nose3?   I wonder, is there some incompatibility with Python 3.12?

**Comment by musicinmybrain** [comment]
> I guess this is with nose3? I wonder, is there some incompatibility with Python 3.12?

We don’t have `nose3` in Fedora (https://fedoraproject.org/wiki/Changes/DeprecateNose happened, and `nose3` conflicts with it since it still provides `import nose`), so this is with a patched copy of old-school `nose`.

I’ll guess I could see if I can reproduce it in a virtualenv, or with a hacked-together local `nose3` RPM package, or something.

The biggest obstacle I have right now is that I am having a hard time establishing exactly where the traceback is coming from.

**Comment by musicinmybrain** [comment]
It looks like `nose3` may be going the way of `nose`, maintenance-wise. It still does not properly support Python 3.11 (https://github.com/jayvdb/nose3/issues/2).

Migrating to `pytest` (https://github.com/nipy/nipy/issues/499) would be great; porting to https://github.com/nose-devs/nose2 could be another possibility. I’m not sure either of these efforts is straightforward enough for me to offer as a drive-by PR, though.

**Comment by effigies** [comment]
I tried running with pytest this morning, but it's not drop in. The doctest plugins will need replacement to work with it. Possibly pytest-doctestplus would cover much of it.

**Comment by musicinmybrain** [comment]
Works for me with e5e063b09d094ff79d2089261828fd2b2c843ab6; see https://github.com/nipy/nipy/issues/526#issuecomment-1759978210.
